version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-services
      - order-services
      - payment-services
      - inventory-services
      - customer-services

  menu-services:
    build:
      context: ./menu-services
    ports:
      - "3001:3001"

  order-services:
    build:
      context: ./order-services
    ports:
      - "3002:3002"

  payment-services:
    build:
      context: ./payment-services
    ports:
      - "3003:3003"

  inventory-services:
    build:
      context: ./inventory-services
    ports:
      - "3004:3004"

  customer-services:
    build:
      context: ./customer-services
    ports:
      - "3005:3005"